/* External QA dependency: Playwright. CHROMIUM_PATH selects the installed QA browser. */
const {chromium}=require('playwright');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
const out=path.resolve(__dirname,'../qa-output');fs.mkdirSync(out,{recursive:true});
const url='file://'+path.resolve(__dirname,'../dist/BLACKLINE-v0.1.0-alpha.1.html');
(async()=>{const b=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/tmp/chromium',headless:true,args:['--no-sandbox','--disable-dev-shm-usage']});const p=await b.newPage({viewport:{width:1280,height:720}});const errors=[];p.on('pageerror',e=>errors.push(e.message));
await p.goto(url);await p.screenshot({path:out+'/title-desktop.png'});await p.click('#play');await p.waitForFunction(()=>BLACKLINE.snapshot().mode==='running');
await p.keyboard.down('ArrowRight');await p.waitForTimeout(300);await p.keyboard.up('ArrowRight');await p.waitForTimeout(70);assert.equal((await p.evaluate(()=>BLACKLINE.snapshot())).steer,0);
await p.click('#pause');const t=await p.evaluate(()=>BLACKLINE.snapshot().t);await p.waitForTimeout(300);assert.equal(await p.evaluate(()=>BLACKLINE.snapshot().t),t);await p.click('#resume');await p.waitForFunction(()=>BLACKLINE.snapshot().mode==='running');
// Start a clean run, using actual browser keyboard events throughout.
await p.click('#pause');await p.click('#quit');await p.click('#play');await p.waitForFunction(()=>BLACKLINE.snapshot().mode==='running');
let held=new Set(),shots=new Set(),start=Date.now();
while(Date.now()-start<100000){const s=await p.evaluate(()=>BLACKLINE.snapshot());if(s.mode==='result')break;assert.equal(s.mode,'running');
const k=await p.evaluate(z=>BlacklineSim.curve(z),s.z);const n=s.v/(220/3.6),desired=(k*n*n*.98-s.x*4-s.lv*.35)/(1.65*(.3+.7*n));let want=new Set();if(desired>.1)want.add('ArrowRight');if(desired<-.1)want.add('ArrowLeft');if(Math.abs(k)>1.2&&s.v>46)want.add('ArrowDown');
for(const key of held)if(!want.has(key))await p.keyboard.up(key);for(const key of want)if(!held.has(key))await p.keyboard.down(key);held=want;
for(const [name,condition] of [['bend',s.z>1380],['ramp',s.z>2750],['air',!!s.jump]])if(condition&&!shots.has(name)){await p.screenshot({path:out+'/'+name+'-desktop.png'});shots.add(name);}
await p.waitForTimeout(40);}
for(const key of held)await p.keyboard.up(key);const result=await p.evaluate(()=>BLACKLINE.snapshot());assert.equal(result.reason,'escaped');assert.equal(result.resultCount,1);await p.screenshot({path:out+'/result-desktop.png'});await p.click('#retry');await p.waitForFunction(()=>BLACKLINE.snapshot().mode==='running');assert.equal(await p.evaluate(()=>BLACKLINE.snapshot().hp),100);await p.close();
// Mobile viewport and synthetic multi-contact interruption checks, not physical-device evidence.
const m=await b.newPage({viewport:{width:852,height:393},hasTouch:true,isMobile:true,deviceScaleFactor:1});m.on('pageerror',e=>errors.push(e.message));await m.goto(url);await m.screenshot({path:out+'/title-mobile.png'});await m.click('#play');await m.waitForFunction(()=>BLACKLINE.snapshot().mode==='running');
const contact=async(action,type,id)=>m.evaluate(({action,type,id})=>{const el=document.querySelector(`[data-action="${action}"]`);if(type==='pointerdown')el.setPointerCapture=()=>{};el.dispatchEvent(new PointerEvent(type,{bubbles:true,cancelable:true,pointerId:id,pointerType:'touch',buttons:type==='pointerup'?0:1}));},{action,type,id});
await contact('right','pointerdown',11);await contact('boost','pointerdown',12);await m.waitForTimeout(100);assert.equal(await m.evaluate(()=>BLACKLINE.snapshot().steer),1);assert.equal(await m.evaluate(()=>BLACKLINE.snapshot().boosting),true);
await contact('right','pointerup',11);await m.waitForTimeout(100);assert.equal(await m.evaluate(()=>BLACKLINE.snapshot().steer),0);assert.equal(await m.evaluate(()=>BLACKLINE.snapshot().boosting),true);await contact('boost','pointerup',12);
await contact('left','pointerdown',13);await contact('brake','pointerdown',14);await contact('brake','pointerup',14);await m.waitForTimeout(100);assert.equal(await m.evaluate(()=>BLACKLINE.snapshot().steer),-1);assert.equal(await m.evaluate(()=>BLACKLINE.snapshot().braking),false);await contact('left','pointerup',13);
await contact('right','pointerdown',15);await m.evaluate(()=>window.dispatchEvent(new Event('blur')));await m.waitForTimeout(80);assert.equal(await m.evaluate(()=>BLACKLINE.snapshot().mode),'paused');assert.equal(await m.evaluate(()=>BLACKLINE.snapshot().steer),0);await m.click('#resume');await m.waitForFunction(()=>BLACKLINE.snapshot().mode==='running');
await contact('left','pointerdown',16);await contact('left','pointercancel',16);await m.waitForTimeout(80);assert.equal(await m.evaluate(()=>BLACKLINE.snapshot().mode),'paused');await m.click('#resume');await m.waitForFunction(()=>BLACKLINE.snapshot().mode==='running');
const menuPrevented=await m.evaluate(()=>{const e=new MouseEvent('contextmenu',{bubbles:true,cancelable:true});document.querySelector('#hp').dispatchEvent(e);return e.defaultPrevented;});assert.equal(menuPrevented,true);await m.waitForTimeout(80);assert.equal(await m.evaluate(()=>BLACKLINE.snapshot().mode),'paused');
await m.click('#resume');await m.waitForFunction(()=>BLACKLINE.snapshot().mode==='running');await m.screenshot({path:out+'/driving-mobile.png'});await m.setViewportSize({width:393,height:852});await m.waitForTimeout(200);assert.equal(await m.evaluate(()=>BLACKLINE.snapshot().mode),'paused');assert.equal(await m.locator('#rotate').isVisible(),true);await m.setViewportSize({width:852,height:393});await m.waitForTimeout(200);assert.equal(await m.evaluate(()=>BLACKLINE.snapshot().mode),'paused');await m.click('#resume');await m.waitForFunction(()=>BLACKLINE.snapshot().mode==='running');
const boxes=await m.locator('[data-action]').evaluateAll(es=>es.map(e=>{const b=e.getBoundingClientRect();return {x:b.x,y:b.y,w:b.width,h:b.height};}));assert.ok(boxes.every(b=>b.x>=0&&b.y>=0&&b.x+b.w<=853&&b.y+b.h<=394));assert.deepEqual(errors,[]);
const report={browser:await b.version(),desktop:{result,realKeyboard:true},syntheticTouch:{bothReleaseOrders:true,cancel:true,blur:true,contextmenu:true,rotation:true,controlsWithinViewport:true},errors,physicalDevices:'Not run',hosted:'Not run'};fs.writeFileSync(out+'/browser-results.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));await b.close();})().catch(e=>{console.error(e);process.exit(1)});
