const {test}=require('node:test');const assert=require('node:assert/strict');const S=require('../src/sim.js');
const ready=(seed=7319)=>Object.assign(S.newState(seed),{mode:'running',encounterIndex:S.ENCOUNTERS.length});
const step=(s,seconds,input={})=>{for(let i=0;i<Math.ceil(seconds*60);i++)S.tick(s,1/60,typeof input==='function'?input(s):input);};
function driver(s,evade=true,boost=false){const k=S.curve(s.z),n=s.v/S.C.max,e=s.enemies.find(e=>e.phase!=='follow');let target=0;if(evade&&e)target=e.type==='rammer'?-(e.side||1)*.62:(e.aim>=0?-.58:.58);else if(evade&&s.projectiles.length)target=s.projectiles[0].x>=0?-.58:.58;const j=S.nextJump(s.z);if(j&&j.start-s.z<270||s.jump)target=0;const steer=S.clamp((k*n*n*.98+(target-s.x)*3-s.lv*.2)/(1.65*(.3+.7*n)),-1,1);return {steer,brake:Math.abs(k)>1.2&&s.v>46,boost:boost&&Math.abs(k)<.2&&!e};}
function run(seed,evade=true,boost=false){const s=ready(seed);s.encounterIndex=0;let frames=0,maxEnemies=0,maxAttack=0;while(s.mode==='running'&&frames++<18001){S.tick(s,1/60,driver(s,evade,boost));maxEnemies=Math.max(maxEnemies,s.enemies.length);maxAttack=Math.max(maxAttack,s.enemies.filter(e=>e.phase!=='follow').length);s.events=[];}return {s,maxEnemies,maxAttack};}
test('accepted acceleration/brake/boost behavior and reset retained',()=>{const s=ready();s.v=40;s.boost=.5;step(s,.5,{brake:true,boost:true});assert.ok(s.v<31);assert.ok(s.boost>=.5);const r=ready();step(r,2);assert.ok(r.v>15);S.begin(s);assert.deepEqual(s,{...S.newState(),mode:'countdown'});});
test('pause freezes all AI, projectiles, timer and charge; long stall pauses',()=>{const s=ready();S.spawn(s,'interceptor');s.v=40;s.boost=.3;s.projectiles.push({z:-2,x:0,v:100,life:2,burst:1});S.pause(s);const before=JSON.stringify(s);step(s,10,{boost:true});assert.equal(JSON.stringify(s),before);S.resume(s);step(s,1.1);assert.equal(s.mode,'running');S.tick(s,1);assert.equal(s.mode,'paused');});
test('wall contact limited to one damage event per second; highest simultaneous damage wins',()=>{const s=ready();s.x=1.15;s.v=50;step(s,.9,{steer:1});assert.equal(s.collisions,1);assert.equal(s.hp,88);step(s,.2,{steer:1});assert.equal(s.collisions,2);const a=ready();S.damage(a,10,'burst');S.damage(a,15,'ram');S.damage(a,12,'barrier');S.resolveDamage(a);assert.equal(a.hp,85);assert.equal(a.lastHit,'ram');});
test('braking reduces curve drift',()=>{const a=ready(),b=ready();for(const s of [a,b]){s.z=1350;s.v=55;}step(a,.3);step(b,.3,{brake:true});assert.ok(Math.abs(b.lv)<Math.abs(a.lv));});
for(const j of S.JUMPS)test(`jump ${j.id+1}: geometry, no-boost success, low speed and missed corridor`,()=>{assert.equal(S.elevation(j.start),S.elevation(j.end));assert.ok(j.safeKmh/3.6*j.flight>j.end-j.start);const a=ready();a.z=j.start-1;a.jumpIndex=j.id;a.v=j.safeKmh/3.6;step(a,1.3);assert.equal(a.landings,1);assert.equal(a.mode,'running');const b=ready();b.z=j.start-1;b.jumpIndex=j.id;b.v=22;step(b,1.4);assert.equal(b.reason,'jump-too-slow');const c=ready();c.z=j.start-.1;c.jumpIndex=j.id;c.x=.8;c.v=60;S.tick(c,1/60);assert.equal(c.reason,'missed-ramp');});
test('swept takeoff/finish and timeout boundary',()=>{const s=ready();s.z=5049.99;s.v=S.C.boostMax;S.tick(s,1/60,{boost:true});assert.ok(s.jump);const a=ready();a.z=S.C.length-.01;a.v=60;a.t=299.9;a.jumpIndex=3;S.tick(a,1/60);assert.equal(a.reason,'escaped');assert.equal(a.resultCount,1);step(a,2);assert.equal(a.resultCount,1);const b=ready();b.t=299.99;step(b,.1);assert.equal(b.reason,'timeout');assert.ok(Math.abs(b.t-300)<1e-6);});
test('repair pickups cap health, require alignment and collect once',()=>{const r=S.REPAIRS[0],s=ready();s.z=r.z-.2;s.v=50;s.hp=90;s.x=r.x;s.jumpIndex=2;step(s,.1);assert.equal(s.hp,100);assert.deepEqual(s.picked,[0]);s.z=r.z-.2;s.hp=60;step(s,.1);assert.equal(s.hp,60);});
test('pursuer movement is bounded, corner speeds lower and gap failure real',()=>{const a=ready();a.z=1500;a.v=50;const e=S.spawn(a,'interceptor',50),old=e.z;S.tick(a,1/60);assert.ok(Math.abs(e.z-old)<1.3);step(a,1);assert.ok(e.v<55);const b=ready();b.z=5200;b.v=50;b.jumpIndex=1;const f=S.spawn(b,'interceptor',151);f.z=5049;f.v=20;f.jumpIndex=0;step(b,1.5);assert.equal(b.stats.enemyCrashes,1);assert.ok(!b.enemies.includes(f));});
test('shots use a locked lane: center is hit and side dodge survives',()=>{for(const evade of [false,true]){const s=ready();s.z=5260;s.v=50;s.jumpIndex=1;s.x=evade?.6:0;const e=S.spawn(s,'interceptor',22);e.x=0;e.v=50;e.grace=0;e.phase='aim';e.age=.71;e.aim=0;s.attackOwner=e.id;step(s,1.1,q=>({steer:evade?S.clamp((.6-q.x)*3-q.lv*.2,-1,1):0}));assert.equal(s.stats.shots,1);assert.equal(s.hp,evade?100:90);}});
test('ram is lethal-capable and moving away evades its committed line',()=>{for(const evade of [false,true]){const s=ready();s.z=12500;s.v=50;s.jumpIndex=2;const e=S.spawn(s,'rammer',2);e.x=.76;e.side=1;e.v=50;e.phase='ram-warn';e.age=0;e.aim=0;e.grace=0;s.attackOwner=e.id;step(s,2,q=>({steer:evade?S.clamp((-.62-q.x)*3-q.lv*.2,-1,1):0}));assert.equal(s.stats.rams,1);assert.equal(s.hp,evade?100:85);}});
test('jump corridor cancels attacks and projectiles, and post-landing immunity is timed',()=>{const s=ready();s.z=4950;s.v=50;const e=S.spawn(s,'interceptor',20);e.phase='aim';e.age=1.19;s.attackOwner=e.id;s.projectiles=[{z:4949,x:0,v:132,life:2,burst:7}];step(s,.1);assert.equal(e.phase,'follow');assert.equal(s.projectiles.length,0);assert.equal(s.hp,100);s.z=5165;s.safeUntil=s.t+1;assert.equal(S.protectedRoad(s),true);s.t+=1.1;assert.equal(S.protectedRoad(s),false);});
test('three shots of one burst cannot cause repeated damage',()=>{const s=ready();s.z=5300;s.v=50;s.jumpIndex=1;s.projectiles=[0,1,2].map(i=>({z:5299-i*.2,x:0,v:132,life:2,burst:42}));step(s,.2);assert.equal(s.hp,90);assert.equal(s.stats.hits,1);assert.equal(s.projectiles.length,0);});
test('seeded no-boost runs cover all six sectors and last 4–5 minutes',()=>{for(const seed of [7319,17,999]){const {s,maxEnemies,maxAttack}=run(seed);assert.equal(s.reason,'escaped',JSON.stringify({seed,t:s.t,z:s.z,hp:s.hp}));assert.equal(s.landings,3);assert.ok(s.t>=240&&s.t<300);assert.ok(s.stats.shots>0&&s.stats.rams>0);assert.ok(maxEnemies<=3&&maxAttack<=1);console.log('Escape',JSON.stringify({seed,seconds:s.t,hp:s.hp,shots:s.stats.shots,rams:s.stats.rams,hits:s.stats.hits}));}assert.equal(new Set(S.SECTIONS.map(x=>S.zone(x.start))).size,6);});
test('ignoring gunfire can be killed by an actual pursuer',()=>{const {s}=run(7319,false);assert.equal(s.reason,'destroyed');assert.equal(s.deathCause,'burst');assert.ok(s.stats.hits>=10);assert.ok(s.t<300);});
module.exports={driver,run};
